name: Auto Approve Pull Requests by SRDEVOPS

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Wait for status checks
        id: waitforstatuschecks-before-approving
        uses: "WyriHaximus/github-action-wait-for-status@v1"
        with:
          ignoreActions: auto-merge,auto-approve,auto-update-pr
          checkInterval: 13
        env:
          GITHUB_TOKEN: "${{ secrets.SR_TOKEN }}"
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.event.pull_request.user.login == 'srdevops' && steps.waitforstatuschecks-before-approving.outputs.status == 'success'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.event.pull_request.user.login == 'srdevops' && steps.waitforstatuschecks-before-approving.outputs.status == 'success'
        with:
          github-token: "${{ secrets.AUTO_APPROVE_TOKEN }}"
