name: AI Code Reviewer

on: 
    pull_request:
        types:
            - opened
            - reopened 
            - synchronize

jobs: 
    code_review:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - name: AI Reviewer
              uses: softrams/github-pr-magic@v0.0.1-beta
              with: 
                github_token: ${{ secrets.SR_TOKEN }}
                openai_api_key: ${{ secrets.OPENAI_API_KEY }}
